### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by restfuladi** [ray-x/nvim#10] opened 2021-12-18 16:44 UTC
After packer is done installing, all future starts of nvim show the errors below, I'm not sure what's going on. 

```
packer.nvim: Error running config for refactoring.nvim: ...ck/packer/opt/refactoring.nvim/lua/refactoring/query.lua:1: module 'nvim-treesitter.parsers' not found:
^Ino field package.preload['nvim-treesitter.parsers']No cache entry
^Ino file './nvim-treesitter/parsers.lua'
^Ino file '/home/user/repos/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-treesitter/parsers.lua'
^Ino file '/usr/local/share/lua/5.1/nvim-treesitter/parsers.lua'
^Ino file '/usr/local/share/lua/5.1/nvim-treesitter/parsers/init.lua'
^Ino file '/home/user/repos/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/parsers.lua'
^Ino file '/home/user/repos/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/parsers/init.lua'
^Ino file '/home/user/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-treesitter/parsers.lua'
^Ino file '/home/user/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-treesitter/parsers/init.lua'
^Ino file '/home/user/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-treesitter/parsers.lua'
^Ino file '/home/user/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-treesitter/parsers/init.lua'
^Ino file './nvim-treesitter/parsers.so'
^Ino file '/usr/local/lib/lua/5.1/nvim-treesitter/parsers.so'
^Ino file '/home/user/repos/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter/parsers.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/user/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvim-treesitter/parsers.so'
^Ino file './nvim-treesitter.so'
^Ino file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
^Ino file '/home/user/repos/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/user/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvim-treesitter.so'
Press ENTER or type command to continue
Error executing vim.schedule lua callback: /home/user/.config/nvim/lua/core/lazy.lua:140: Vim(lua):E5108: Error executing lua /home/user/.config/nvim/lua/utils/log.lua:24: bad argument #1 to 'close' (FILE
* expected, got nil)
stack traceback:
        [C]: in function 'close'
        /home/user/.config/nvim/lua/utils/log.lua:24: in function 'lprint'
        /home/user/.config/nvim/lua/core/lazy.lua:45: in function 'Lazyload'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        /home/user/.config/nvim/lua/core/lazy.lua:140: in function 'fn'
        vim.lua:415: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
stack traceback:
        [C]: in function 'cmd'
        /home/user/.config/nvim/lua/core/lazy.lua:140: in function 'fn'
        vim.lua:415: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
Press ENTER or type command to continue
packer.nvim: Error running config for telescope-frecency.nvim: ...nvim/site/pack/packer/opt/sqlite.lua/lua/sqlite/defs.lua:29: libsqlite3.so: cannot open shared object file: No such file or directory
Press ENTER or type command to continue
packer.nvim: Error running config for neogen: ...al/share/nvim/site/pack/packer/opt/neogen/lua/neogen.lua:2: neogen requires nvim-treesitter to operate :(
Press ENTER or type command to continue
```

**Comment by ray-x** [comment] 2021-12-18 21:54
You may need to run `PackerCompile` after all package installed.
If it does not fix the problem, maybe it caused by refactor.nvim. please switch to `nulls` branch to see if you still see that error.

**Comment by restfuladi** [comment] 2021-12-19 16:26
Just to make sure, after the first automated Packer run that installs all packages, run PackerCompile and restart Neovim? Thanks.

**Comment by ray-x** [comment] 2021-12-19 20:40
after installing all packages, restart nvim and if you see errors, please run PackerCompile and restart nvim again.
If you are using latest version, The behavior should be
1) install all packages
2) restart, the startup script should run `PackerCompile` for you automatically 
3) restart and treesitter will be installed automatically and you can begin use it.

**Comment by khatibomar** [comment] 2022-01-11 13:24
I have same issue , I said need to give it a retry in virtual machine to get used to it faced failing 3 plugins installations then having same error.

**Comment by ray-x** [comment] 2022-01-11 14:27
Is it because of windows?

**Comment by ray-x** [comment] 2022-01-11 14:45
May related to log file folder not existed. Added a fix for it.

**Comment by khatibomar** [comment] 2022-01-11 15:47
Nop I am on linux first time I tried to install on local machine couple of months ago , now on mx-linux in an VM ware to play with the setup before switch my main workflow.

**Comment by ray-x** [comment] 2022-01-11 21:53
It caused by incorrect permission of `~/tmp`

Please pull the latest version and remove the folder `~/tmp` or change the folder permission to `755`, and run the setup again.
Thanks!

**Comment by khatibomar** [comment] 2022-01-11 22:31
it looks like the error is fixed now , but why using the `~/tmp` not the OS default tmp folder? like /tmp and `%APPDATA` on windows?
other thing I got this error
```
libsqlite3.so: cannot open shared object file: No such file or directory
```
it's straight forward should install this obv

**Comment by ray-x** [comment] 2022-01-11 22:57
I am not aware sqlite is not default installed. I will update the README.md
as for use `~/tmp` as log folder. I felt default tmp folder path is too long at that time.

**Comment by khatibomar** [comment] 2022-01-12 14:09
putting the tmp folder in home is bad thing first you are creating a tmp folder but OS provide one for you and maybe some error happens and program can't clean the tmp folder you created , so using default OS folder instead. Also it polute the home for users. 
Maybe make helper function to get the tmp folder for OS same as in Go the function that return the user [TempDir](https://pkg.go.dev/os#TempDir)
if the logs are necessary to be stored then store them in default config folder but please not in home 👍🏻

**Comment by khatibomar** [comment] 2022-01-12 14:24
```
Error detected while processing /home/mx/.local/share/nvim/site/pack/packer/opt/starry.nvim/colors/moonlig
ht.vim:                                                                                                   
line    4:                                                                                                
E5108: Error executing lua [string ":lua"]:1: module 'starry' not found:                                  
        no field package.preload['starry']                                                                
        no file './starry.lua'                                                                            
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/starry.lua'           
        no file '/usr/local/share/lua/5.1/starry.lua'                                                     
        no file '/usr/local/share/lua/5.1/starry/init.lua'                                                
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/starry.lua'                      
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/starry/init.lua'                 
        no file '/home/mx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/starry.lua'              
        no file '/home/mx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/starry/init.lua'         
        no file '/home/mx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/starry.lua'     
        no file '/home/mx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/starry/init.lua'
                                                                                                          
        no file './starry.so'                                                                             
        no file '/usr/local/lib/lua/5.1/starry.so'                                                        
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/starry.so'                         
        no file '/usr/local/lib/lua/5.1/loadall.so'                                                       
        no file '/home/mx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/starry.so'                 
stack traceback:                                                                                          
        [C]: in function 'require'                                                                        
        [string ":lua"]:1: in main chunk                                                                  
```
got this error when chaning colorscheme to moonlight also other themes.

**Comment by ray-x** [comment] 2022-01-12 21:37
Thanks, will change the log folder to neovim default log folder.
As for the error change scheme. All colorscheme is loaded lazily (except the current one). You may need to `packadd starry.nvim` before you switch to that colorscheme.

**Comment by restfuladi** [comment] 2022-01-21 16:43
Still getting stuck around installing 50/128 plugins. I disabled worktreer and changed vim-clap to 'clap#installer#build_all' so it would compile an arm64 version Apple M1 but now I can't tell what is causing the issue. Changed packer log to debug and all it says `[DEBUG Fri Jan 21 11:39:59 2022 1.094531057511e+15] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:569: Running tasks`

**Comment by ray-x** [comment] 2022-01-22 11:39
I do not have a M1 to reproduce. Also, the setup should download clap binary instead of rebuild from scratch.

**Comment by restfuladi** [comment] 2022-01-22 17:47
Unfortunately vim-clap and a few others don't provide arm64-darwin binaries. I'm happy to figure out which plugins are breaking but I don't know where to look.

**Comment by ray-x** [comment] 2022-08-21 22:23
You are loading nvim 0.7.x
I am not awared that some of the setup not working in 0.7.x. It was fixed.
Please update the repo and update aurora. It should be fixed.

**Closed** 2022-10-03 22:56 UTC
